# Generated by Django 4.1.1 on 2024-04-04 10:18

import MainApp.formatChecker
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_alter_comment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=MainApp.formatChecker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to='images'),
        ),
    ]
